# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'paul_van_bike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for paul_van_bike
  #pod 'RSKImageCropper'
  #pod 'QBImagePickerController'
  # React
  pod 'React', path: '../node_modules/react-native', subspecs: [
  #pod 'React', :path => './Other Sources/ReactNative', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
	'RCTWebSocket',
    'ART',
    'RCTActionSheet',
    #'RCTAdSupport',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTPushNotification',
    'RCTSettings',
    'RCTVibration',
    'RCTLinkingIOS',
  ]
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  #pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
 
  #target 'paul_van_bikeTests' do
    #inherit! :search_paths
	 #Pods for testing
  #end

end

#target 'paul_van_bike-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for paul_van_bike-tvOS

  #target 'paul_van_bike-tvOSTests' do
    #inherit! :search_paths
	 #Pods for testing
  #end

#end
